config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://jalankemana.com'
  site_title: Hey Jalan Kemana
  site_subtitle_1: Portfolio
  site_subtitle_2: 'Jakarta, Indonesia'
  site_description: >
    Jalan Kemana is a creative community of friends passionate about analog
    photography and travel. We capture timeless moments through our explorations
    and offer a unique instant analog photobooth experience, blending art and
    adventure.
  site_email: hey@jalankemana.com
  site_social_url: 'https://instagram.com/heyjalankemana'
  site_icon_svg: ''
  site_icon_png: '/assets/uploads/favicon-32x32.png'
  site_ga4_id: ''
  seo:
    site_title: 'Jalan Kemana – Analog Photography, Travel Collective & Instant Photobooth'
    site_description: >-
      Jalan Kemana is a creative collective exploring analog photography and
      travel adventures. Discover our instant analog photobooth experience and
      join our journey of timeless moments.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Instagram
